"""enforce one DM per rule and user

Revision ID: 9860387b5d26
Revises: c4774b5d7ce4
Create Date: 2026-08-17 17:46:52.894133

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9860387b5d26'
down_revision: Union[str, Sequence[str], None] = 'c4774b5d7ce4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_rule_recipient'), 'dm_jobs', type_='unique')
    op.create_unique_constraint('uq_dm_jobs_rule_recipient', 'dm_jobs', ['rule_id', 'recipient_user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_dm_jobs_rule_recipient', 'dm_jobs', type_='unique')
    op.create_unique_constraint(op.f('uq_rule_recipient'), 'dm_jobs', ['rule_id', 'recipient_user_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
