"""add DM send attempts

Revision ID: c4774b5d7ce4
Revises: 7fb87a7ec7f2
Create Date: 2026-08-17 11:35:22.136970

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c4774b5d7ce4'
down_revision: Union[str, Sequence[str], None] = '7fb87a7ec7f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dm_send_attempts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('attempted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dm_send_attempts_attempted_at'), 'dm_send_attempts', ['attempted_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_dm_send_attempts_attempted_at'), table_name='dm_send_attempts')
    op.drop_table('dm_send_attempts')
    # ### end Alembic commands ###
